// PRODUCTS
export const PRODUCTS_SET_LOADING = "PRODUCTS_SET_LOADING";
export const PRODUCTS_SET_LOADED = "PRODUCTS_SET_LOADED";
export const PRODUCTS_SET_PRODUCTS = "PRODUCTS_SET_PRODUCTS";

// CART
export const CART_ADD_PRODUCT = "CART_ADD_PRODUCT";
export const CART_REMOVE_PRODUCT = "CART_REMOVE_PRODUCT";
export const CART_CLEAN = "CART_CLEAN";
